apiVersion: v1
kind: Service
metadata:
  name: hello-service-b
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: hello-world-b # Busca los pods que tengan esta etiqueta.
